# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/diffy/all/diffy.rbi
#
# diffy-3.4.3

module Diffy
end
module Diffy::Format
  def color; end
  def html; end
  def html_simple; end
  def text; end
end
class Diffy::HtmlFormatter
  def clean_line(line); end
  def highlight(lines); end
  def highlighted_words; end
  def initialize(diff, options = nil); end
  def reconstruct_characters(line_diff, type); end
  def split_characters(chunk); end
  def to_s; end
  def wrap_line(line); end
  def wrap_lines(lines); end
end
class Diffy::Diff
  def diff; end
  def diff_bin; end
  def diff_options; end
  def each; end
  def each_chunk; end
  def initialize(string1, string2, options = nil); end
  def options; end
  def self.default_format; end
  def self.default_format=(arg0); end
  def self.default_options; end
  def self.default_options=(arg0); end
  def string1; end
  def string2; end
  def tempfile(string); end
  def to_s(format = nil); end
  include Enumerable
end
class Diffy::SplitDiff
  def initialize(left, right, options = nil); end
  def left; end
  def right; end
  def split; end
  def split_left; end
  def split_right; end
end
