# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: true
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/ruby-filemagic/all/ruby-filemagic.rbi
#
# ruby-filemagic-0.7.3

class FileMagic
  def buffer(*arg0); end
  def check(*arg0); end
  def close; end
  def closed?; end
  def compile(*arg0); end
  def descriptor(*arg0); end
  def fd(fd); end
  def file(*arg0); end
  def flags; end
  def flags=(arg0); end
  def initialize(*arg0); end
  def inspect; end
  def io(io, length = nil, rewind = nil); end
  def list(*arg0); end
  def load(*arg0); end
  def self.auto_magic_version; end
  def self.clear!; end
  def self.flags(arg0); end
  def self.fm(*flags); end
  def self.library_version; end
  def self.magic_version(default = nil); end
  def self.mime(*flags, &block); end
  def self.new(*arg0); end
  def self.open(*flags); end
  def self.path; end
  def self.user_magic_version(key = nil); end
  def simplified=(arg0); end
  def simplified?; end
  def valid?(*arg0); end
end
module FileMagic::Version
  def self.to_a; end
  def self.to_s; end
end
