plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  NewCops: enable

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'
    - 'lib/hank/cli.rb'
    - 'lib/hank/file_selector.rb'
    - 'lib/hank/path_utils.rb'
    - 'lib/hank/symlink_manager.rb'
    - 'lib/hank/validator.rb'

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'
    - 'lib/hank/cli.rb'
    - 'lib/hank/file_selector.rb'
    - 'lib/hank/symlink_manager.rb'
    - 'lib/hank/validator.rb'

Metrics/CyclomaticComplexity:
  Exclude:
    - 'lib/hank/cli.rb'
    - 'lib/hank/file_selector.rb'
    - 'lib/hank/symlink_manager.rb'

Metrics/PerceivedComplexity:
  Exclude:
    - 'lib/hank/cli.rb'
    - 'lib/hank/file_selector.rb'
    - 'lib/hank/symlink_manager.rb'

Metrics/ClassLength:
  Exclude:
    - 'lib/hank/cli.rb'
    - 'lib/hank/file_selector.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/hank/file_selector.rb'
    - 'lib/hank/validator.rb'

Style/Documentation:
  Exclude:
    - 'lib/hank/version.rb'
    - 'test/**/*'

Gemspec/DevelopmentDependencies:
  EnforcedStyle: gemspec
